"""L0 — SkyPilot execution adapter.

Same shape as `LocalAdapter`, but runs the evaluator on BYO cloud / Kubernetes /
Slurm via SkyPilot, so the keep/revert loop can submit experiments at scale.

CI verifies task generation, timeout/crash mapping, and EvalResult parsing with
an injectable runner. Real SkyPilot SSH/Kubernetes/cloud launches still require
manual release evidence on configured infrastructure.

Intended flow (per experiment):
  1. Build a SkyPilot task that syncs `cwd`, sets up deps, and runs
     `python evaluator.py`, capturing stdout.
  2. Launch on the requested infra, PINNING a hardware class (or use a deterministic
     compute budget) so scores stay comparable across machines.
  3. Fetch the evaluator's stdout, take the last JSON line, and parse it with
     `EvalResult.from_json` — identical to the local adapter.
  4. Enforce the budget; a timeout/crash becomes a veto.
"""
from __future__ import annotations

import shutil
import subprocess
import uuid
from pathlib import Path
from typing import Callable

from ..contract import EvalResult, Veto
from .base import ExecutionAdapter

Runner = Callable[[list[str], Path, float], subprocess.CompletedProcess]


def _default_runner(cmd: list[str], cwd: Path, timeout: float) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, timeout=timeout)


def _parse_last_eval_result(stdout: str) -> EvalResult:
    lines = [ln for ln in stdout.splitlines() if ln.strip()]
    if not lines:
        return EvalResult(None, [Veto("no_output", True, "SkyPilot job emitted nothing")])
    try:
        return EvalResult.from_json(lines[-1])
    except Exception as e:
        return EvalResult(None, [Veto("bad_output", True, str(e)[:200])])


class SkyPilotAdapter(ExecutionAdapter):
    def __init__(self, *, infra: str = "k8s", accelerators: str | None = "L4:1",
                 budget_s: float = 3600.0, setup: str = "",
                 cluster_name: str | None = None, python: str = "python",
                 runner: Runner | None = None):
        # `accelerators` pins a hardware class for comparability (see eval-first.md).
        self.infra = infra
        self.accelerators = accelerators
        self.budget_s = budget_s
        self.setup = setup
        self.cluster_name = cluster_name
        self.python = python
        self.runner = runner or _default_runner

    def task_yaml(self, evaluator: str) -> str:
        """Reviewable task spec.

        `infra` accepts normal SkyPilot values such as `k8s` and the existing-
        machine SSH Node Pool form `ssh/<pool>`.
        """
        resources = [f"  infra: {self.infra}"]
        if self.accelerators:
            resources.append(f"  accelerators: {self.accelerators}")
        return "\n".join([
            "# SkyPilot task (generated by Talos)",
            "resources:",
            *resources,
            "workdir: .",
            "setup: |",
            f"  {self.setup or 'true'}",
            "run: |",
            f"  {self.python} {evaluator}",
            "",
        ])

    def launch_command(self, task_path: str | Path) -> list[str]:
        name = self.cluster_name or f"talos-{uuid.uuid4().hex[:8]}"
        return ["sky", "launch", "-y", "--cluster", name, str(task_path)]

    def run(self, evaluator: str, cwd) -> EvalResult:
        if shutil.which("sky") is None:
            return EvalResult(None, [Veto("skypilot_missing", True, "sky CLI not found")])

        workdir = Path(cwd)
        task_path = workdir / ".talos-skypilot-task.yaml"
        task_path.write_text(self.task_yaml(evaluator))
        try:
            try:
                proc = self.runner(self.launch_command(task_path.name), workdir, self.budget_s)
            except subprocess.TimeoutExpired:
                return EvalResult(None, [Veto("timeout", True, f"exceeded {self.budget_s}s")])
            if proc.returncode != 0:
                detail = (proc.stderr or proc.stdout or "")[-200:]
                return EvalResult(None, [Veto("crash", True, detail)])
            return _parse_last_eval_result(proc.stdout)
        finally:
            task_path.unlink(missing_ok=True)
