"""L0 — SkyPilot execution adapter (v0 SCAFFOLD — UNVERIFIED).

Same shape as `LocalAdapter`, but runs the evaluator on BYO cloud / Kubernetes /
Slurm via SkyPilot, so the keep/revert loop can submit experiments at scale.

!!! This code has NOT been run end-to-end in this repo (no cloud credentials or
    cluster is available in CI). It is a reviewable starting point, not a tested
    component. See docs/survey/compute-backends.md.

Intended flow (per experiment):
  1. Build a SkyPilot task that syncs `cwd`, sets up deps, and runs
     `python evaluator.py`, capturing stdout.
  2. Launch on the requested infra, PINNING a hardware class (or use a deterministic
     compute budget) so scores stay comparable across machines.
  3. Fetch the evaluator's stdout, take the last JSON line, and parse it with
     `EvalResult.from_json` — identical to the local adapter.
  4. Enforce the budget; a timeout/crash becomes a veto.
"""
from __future__ import annotations

import shutil
import textwrap
from pathlib import Path

from ..contract import EvalResult, Veto


class SkyPilotAdapter:
    def __init__(self, *, infra: str = "k8s", accelerators: str | None = "L4:1",
                 budget_s: float = 3600.0, setup: str = ""):
        # `accelerators` pins a hardware class for comparability (see eval-first.md).
        self.infra = infra
        self.accelerators = accelerators
        self.budget_s = budget_s
        self.setup = setup

    def task_yaml(self, evaluator: str) -> str:
        """Reviewable task spec (does not launch anything)."""
        return textwrap.dedent(f"""\
            # SkyPilot task (generated by SkyPilotAdapter — v0)
            resources:
              accelerators: {self.accelerators}
            workdir: .
            setup: |
              {self.setup or 'true'}
            run: |
              python {evaluator}
        """)

    def run(self, evaluator: str, cwd) -> EvalResult:  # pragma: no cover - unverified
        if shutil.which("sky") is None:
            raise NotImplementedError(
                "SkyPilotAdapter is a v0 scaffold and SkyPilot is not installed. "
                "Install SkyPilot, configure an infra (k8s/cloud/Slurm), then implement "
                "launch + log-fetch here. See docs/survey/compute-backends.md.")
        # Intended (UNVERIFIED): write self.task_yaml(evaluator) into `cwd`, run
        # `sky launch -y --infra <infra> <yaml>` with a timeout, `sky logs` to capture
        # stdout, take the last JSON line, and return EvalResult.from_json(line);
        # turn a timeout/nonzero exit into a Veto, exactly like LocalAdapter.
        raise NotImplementedError(
            "SkyPilotAdapter.run is not yet implemented/verified. "
            "See the module docstring for the intended flow and "
            "docs/survey/compute-backends.md.")
